workflows:

  flutter-ios-simulator:

    name: Flutter iOS Simulator

    environment:

      environment:
      
      flutter: 3.27.0
      
      xcode: latest

    scripts:

      - flutter build ios --simulator --flavor staging  # --flavor is optional

    artifacts:

      - build/ios/iphonesimulator/Runner.app
