workflows:
  ios-workflow:
    name: iOS Build & Publish
    max_build_duration: 60
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Codemagic
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.crossist.stocksayar
      vars:
        APP_STORE_APPLE_ID: "BURAYA_APP_APPLE_ID"  # App Store Connect'ten alınır
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios && pod install
      - name: Set build number
        script: |
          LATEST_BUILD=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_APPLE_ID" || echo 0)
          agvtool new-version -all $((LATEST_BUILD + 1))
      - name: Flutter build IPA
        script: |
          flutter build ipa \
            --release \
            --export-options-plist=$CM_BUILD_DIR/ios/ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        expire_build_submitted_for_review: true
      email:
        recipients:
          - gdiyar@gmail.com
        notify:
          success: true
          failure: true
