workflows:
  ios-workflow:
    name: iOS Build Test (M2 Instance)
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Crossist Stock Sayar
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.crossist.stocksayar
      vars:
        APP_STORE_APPLE_ID: 6759662843
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios && pod install
      - name: Set build number (Local Test)
        script: |
          cd ios && agvtool new-version -all 1
      - name: Flutter build IPA
        script: |
          flutter build ipa --release --build-number=1 --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - gdiyar@gmail.com
        notify:
          success: true
          failure: true
