workflows:
  ios-workflow:
    name: iOS Build Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Flutter build iOS
        script: |
          # --no-codesign ile sadece .app üretir
          flutter build ios --release --no-codesign
      - name: Package artifacts
        script: |
          # .app dosyasını Payload klasörüne koyup .ipa olarak zipleyelim
          # Bu yöntem geçici testler ve "App Viewer" görünümü için yeterlidir
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r Runner.ipa Payload
          mv Runner.ipa build/ios/iphoneos/
    artifacts:
      - build/ios/iphoneos/*.ipa
    publishing:
      email:
        recipients:
          - gdiyar@gmail.com
