workflows:
  flutter-ios-simulator:
    name: Flutter iOS Simulator
    max_build_duration: 60
    
    environment:
      flutter: stable
      xcode: latest
      
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Flutter build iOS
        script: |
          flutter build ios --release --no-codesign
          
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - build/ios/iphonesimulator/Runner.app
